spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: localhost:9092
    group-id: event
  datasource:   #h2
    url: jdbc:h2:tcp://localhost/~/event
    username: root
    password: root
    driver-class-name: org.h2.Driver
