spring:
  application:
    name: springboot-mq
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: springboot-mq-consumer
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when_authorized
